-- ─────────────────────────────────────────────────────────────────────────────
-- profiles — extends Supabase auth.users, one row per authenticated user
-- ─────────────────────────────────────────────────────────────────────────────
create table public.profiles (
  id              uuid primary key references auth.users on delete cascade,
  email           text,
  is_super_admin  boolean not null default false,
  created_at      timestamptz not null default now()
);

-- Auto-create a profile row whenever a new auth user is created
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─────────────────────────────────────────────────────────────────────────────
-- licensees — the SaaS subscriber organizations (agencies paying for Intrinsic)
-- ─────────────────────────────────────────────────────────────────────────────
create table public.licensees (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- companies — one row per portfolio company being financially modeled
--
-- The `config` JSONB column stores the company-level data from the v2 config
-- blob: { shared: {...}, serviceLines: [...] }
-- It does NOT store the multi-company wrapper or UI navigation state —
-- those are managed client-side.
-- ─────────────────────────────────────────────────────────────────────────────
create table public.companies (
  id          text primary key,           -- co_xxxxxxxx (generated by the app)
  name        text not null,
  archived    boolean not null default false,
  config      jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Auto-update updated_at on every write
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger companies_set_updated_at
  before update on public.companies
  for each row execute procedure public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- licensee_companies — M2M: which licensees can access which companies
--
-- Under Model 1, only SuperAdmin creates companies and assigns access.
-- Licensees cannot see companies they have no row here for.
-- ─────────────────────────────────────────────────────────────────────────────
create table public.licensee_companies (
  licensee_id   uuid not null references public.licensees on delete cascade,
  company_id    text not null references public.companies on delete cascade,
  role          text not null default 'editor'
                  check (role in ('editor', 'read_only')),
  assigned_at   timestamptz not null default now(),
  primary key (licensee_id, company_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ─────────────────────────────────────────────────────────────────────────────

-- profiles: users can only read/update their own row
alter table public.profiles enable row level security;

create policy "profiles: own row read"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles: own row update"
  on public.profiles for update
  using (auth.uid() = id);

-- Super admins bypass all company RLS (evaluated via profiles lookup)
-- Regular users: read/update only companies assigned to their licensee
alter table public.companies enable row level security;

create policy "companies: super admin full access"
  on public.companies for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_super_admin = true
    )
  );

create policy "companies: licensee read access"
  on public.companies for select
  using (
    exists (
      select 1
      from public.licensee_companies lc
      join public.licensees l on l.id = lc.licensee_id
      join public.profiles p on p.email = l.name  -- temp: replace with proper licensee_id on profile in Track B
      where lc.company_id = companies.id
        and p.id = auth.uid()
    )
  );

create policy "companies: licensee editor write access"
  on public.companies for update
  using (
    exists (
      select 1
      from public.licensee_companies lc
      join public.licensees l on l.id = lc.licensee_id
      join public.profiles p on p.email = l.name
      where lc.company_id = companies.id
        and lc.role = 'editor'
        and p.id = auth.uid()
    )
  );

-- licensee_companies: super admin only
alter table public.licensee_companies enable row level security;

create policy "licensee_companies: super admin full access"
  on public.licensee_companies for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_super_admin = true
    )
  );

-- licensees: super admin only
alter table public.licensees enable row level security;

create policy "licensees: super admin full access"
  on public.licensees for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_super_admin = true
    )
  );
